apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ .Values.labels.app }}
    name: {{ .Values.labels.name }}
    version: {{ .Values.labels.version }}
    component: {{ .Values.labels.component }}
data:
  DATABASE_URL: {{ .Values.env.secret.DATABASE_URL | b64enc }}
  COIN_MARKET_CAP_API_KEY: {{ .Values.env.secret.COIN_MARKET_CAP_API_KEY | b64enc }}
  COINBASE_PRO_API_KEY: {{ .Values.env.secret.COINBASE_PRO_API_KEY | b64enc }}
  COINBASE_PRO_API_PASSPHRASE: {{ .Values.env.secret.COINBASE_PRO_API_PASSPHRASE | b64enc }}
  COINBASE_PRO_API_SECRET: {{ .Values.env.secret.COINBASE_PRO_API_SECRET | b64enc }}
  COVALENT_API_KEY: {{ .Values.env.secret.COVALENT_API_KEY | b64enc }}
  ETHEREUM_CHAIN_ID: {{ .Values.env.secret.ETHEREUM_CHAIN_ID | b64enc }}
  ETHERSCAN_API_KEY: {{ .Values.env.secret.ETHERSCAN_API_KEY | b64enc }}
  INFURA_PROJECT_ID: {{ .Values.env.secret.INFURA_PROJECT_ID | b64enc }}
  INFURA_PROJECT_SECRET: {{ .Values.env.secret.INFURA_PROJECT_SECRET | b64enc }}
  INFURA_RPC_URL: {{ .Values.env.secret.INFURA_RPC_URL | b64enc }}
  LUNACRUSH_API_KEY: {{ .Values.env.secret.LUNACRUSH_API_KEY | b64enc }}
  NOMICS_API_KEY: {{ .Values.env.secret.NOMICS_API_KEY | b64enc }}
