version: '3.8'
services:
  database-development:
    container_name: 'database-development'
    networks:
      - database-development
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=node_api
      - POSTGRES_PASSWORD=node_api_password
      - POSTGRES_DATABASE=node_api
    ports:
      - '5432:5432'
    volumes: 
      - database-development:/var/lib/postgresql/data
volumes:
  database-development:
    driver: local
networks:
  database-test:
