version: '3.8'
services:
  database-development:
    container_name: 'database-development'
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=node_api
      - POSTGRES_PASSWORD=node_api_password
      - POSTGRES_DATABASE=node_api
    ports:
      - '5432:5432'
    volumes: 
      - database-development:/var/lib/postgresql/data
  database-test:
    container_name: 'database-test'
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=node_api
      - POSTGRES_PASSWORD=node_api_password
      - POSTGRES_DB=node_api
    ports:
      - '5433:5432'
    volumes: 
      - /tmp:/tmp
  redis-development:
    container_name: 'redis-development'
    image: redis:7.0.0
    ports:
      - '6379:6379'
  redis-test:
    container_name: 'redis-test'
    image: redis:7.0.0
    ports:
      - '6380:6379'

volumes:
  database-development:
    driver: local
  database-test:
    driver: local

