labels:
  app: blocksight-api
  name: node
  version: "1.0.0"
  component: server

deployment:
  name: blocksight-deployment
  apiVersion: apps/v1
  spec:
    replicas: 1
    strategy:
      type: Recreate
    restartPolicy: Always
    containers:
      image: 'blocksight-development:latest'
      imagePullPolicy: Never
      ports:
        containerPortApp: 3001

service:
  name: blocksight-service
  apiVersion: v1
  spec:
    type: LoadBalancer
    ports:
      protocol: TCP
      name: tcp-3001
      port: 3001
      targetPort: 3001
      nodePort: 30001

secret:
  name: blocksight-secret
